### Real Data, Real Practice Imports and Setup.

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

# Import our input dataset
attrition_df = pd.read_csv("resources/HR-employee-Attrition.csv")
attrition_df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [2]:
# Generate our categorical variable list
attrition_cat = attrition_df.dtypes[attrition_df.dtypes == "object"].index.tolist()

### Real Data, Real Practice Preprocessing.

In [3]:
# Check the number of unique values in each column
attrition_df[attrition_cat].nunique()

Attrition         2
BusinessTravel    3
Department        3
EducationField    6
Gender            2
JobRole           9
MaritalStatus     3
Over18            1
OverTime          2
dtype: int64

In [4]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(attrition_df[attrition_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(attrition_cat)
encode_df.head()

c:\Users\vlour\anaconda3\envs\mlenv\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,Attrition_No,Attrition_Yes,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [5]:
# Merge one-hot encoded features and drop the originals
attrition_df = attrition_df.merge(encode_df,left_index=True, right_index=True)
attrition_df = attrition_df.drop(attrition_cat,1)
attrition_df.head()

c:\Users\vlour\anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [6]:
# Split our preprocessed data into our features and target arrays
y = attrition_df["Attrition_Yes"].values
X = attrition_df.drop(["Attrition_Yes","Attrition_No"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

c:\Users\vlour\anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

In [7]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

### Real Data, Real Practice Deep Learning Model Design.

In [8]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 448

 dense_1 (Dense)             (None, 5)                 45

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 499
Trainable params: 499
Non-trainable params: 0
_________________________________________________________________

In [9]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

### Real Data, Real Practice Train and Evaluate the Model

In [10]:
# Train the model
fit_model = nn.fit(X_train,y_train,epochs=100)

Epoch 1/100
35/35 [==============================] - 0s 750us/step - loss: 306.6438 - accuracy: 0.7314
Epoch 2/100
35/35 [==============================] - 0s 721us/step - loss: 143.7158 - accuracy: 0.7632
Epoch 3/100
35/35 [==============================] - 0s 731us/step - loss: 46.7039 - accuracy: 0.7450
Epoch 4/100
35/35 [==============================] - 0s 706us/step - loss: 25.4254 - accuracy: 0.7668
Epoch 5/100
35/35 [==============================] - 0s 794us/step - loss: 16.0922 - accuracy: 0.7559
Epoch 6/100
35/35 [==============================] - 0s 706us/step - loss: 10.9188 - accuracy: 0.7632
Epoch 7/100
35/35 [==============================] - 0s 721us/step - loss: 6.7561 - accuracy: 0.7613
Epoch 8/100
35/35 [==============================] - 0s 692us/step - loss: 5.2978 - accuracy: 0.7314
Epoch 9/100
35/35 [==============================] - 0s 751us/step - loss: 4.5390 - accuracy: 0.7468
Epoch 10/100
35/35 [==============================] - 0s 707us/step - loss: 3.6515 - accuracy: 0.7305
Epoch 11/100
35/35 [==============================] - 0s 721us/step - loss: 4.0283 - accuracy: 0.7387
Epoch 12/100
35/35 [==============================] - 0s 750us/step - loss: 3.8870 - accuracy: 0.7232
Epoch 13/100
35/35 [==============================] - 0s 722us/step - loss: 2.7322 - accuracy: 0.7359
Epoch 14/100
35/35 [==============================] - 0s 700us/step - loss: 3.2551 - accuracy: 0.7423
Epoch 15/100
35/35 [==============================] - 0s 735us/step - loss: 2.6072 - accuracy: 0.7341
Epoch 16/100
35/35 [==============================] - 0s 706us/step - loss: 2.5063 - accuracy: 0.7314
Epoch 17/100
35/35 [==============================] - 0s 750us/step - loss: 2.2542 - accuracy: 0.7459
Epoch 18/100
35/35 [==============================] - 0s 707us/step - loss: 2.2340 - accuracy: 0.7178
Epoch 19/100
35/35 [==============================] - 0s 721us/step - loss: 2.3614 - accuracy: 0.7559
Epoch 20/100
35/35 [==============================] - 0s 721us/step - loss: 1.7821 - accuracy: 0.7577
Epoch 21/100
35/35 [==============================] - 0s 721us/step - loss: 1.9037 - accuracy: 0.7432
Epoch 22/100
35/35 [==============================] - 0s 768us/step - loss: 2.0083 - accuracy: 0.7450
Epoch 23/100
35/35 [==============================] - 0s 692us/step - loss: 1.8244 - accuracy: 0.7586
Epoch 24/100
35/35 [==============================] - 0s 691us/step - loss: 1.9189 - accuracy: 0.7559
Epoch 25/100
35/35 [==============================] - 0s 711us/step - loss: 2.3296 - accuracy: 0.7178
Epoch 26/100
35/35 [==============================] - 0s 737us/step - loss: 1.6401 - accuracy: 0.7468
Epoch 27/100
35/35 [==============================] - 0s 694us/step - loss: 2.1137 - accuracy: 0.7468
Epoch 28/100
35/35 [==============================] - 0s 721us/step - loss: 1.9812 - accuracy: 0.7486
Epoch 29/100
35/35 [==============================] - 0s 725us/step - loss: 2.1643 - accuracy: 0.7114
Epoch 30/100
35/35 [==============================] - 0s 733us/step - loss: 2.8156 - accuracy: 0.7450
Epoch 31/100
35/35 [==============================] - 0s 690us/step - loss: 2.1675 - accuracy: 0.7332
Epoch 32/100
35/35 [==============================] - 0s 715us/step - loss: 1.2368 - accuracy: 0.7613
Epoch 33/100
35/35 [==============================] - 0s 735us/step - loss: 1.1315 - accuracy: 0.7514
Epoch 34/100
35/35 [==============================] - 0s 692us/step - loss: 1.6505 - accuracy: 0.7432
Epoch 35/100
35/35 [==============================] - 0s 719us/step - loss: 1.8637 - accuracy: 0.7359
Epoch 36/100
35/35 [==============================] - 0s 707us/step - loss: 1.0920 - accuracy: 0.7604
Epoch 37/100
35/35 [==============================] - 0s 692us/step - loss: 1.3962 - accuracy: 0.7296
Epoch 38/100
35/35 [==============================] - 0s 721us/step - loss: 1.6858 - accuracy: 0.7523
Epoch 39/100
35/35 [==============================] - 0s 701us/step - loss: 2.3624 - accuracy: 0.7132
Epoch 40/100
35/35 [==============================] - 0s 730us/step - loss: 2.1323 - accuracy: 0.7523
Epoch 41/100
35/35 [==============================] - 0s 692us/step - loss: 1.2182 - accuracy: 0.7486
Epoch 42/100
35/35 [==============================] - 0s 744us/step - loss: 0.9018 - accuracy: 0.7695
Epoch 43/100
35/35 [==============================] - 0s 735us/step - loss: 1.0785 - accuracy: 0.7659
Epoch 44/100
35/35 [==============================] - 0s 693us/step - loss: 1.2682 - accuracy: 0.7922
Epoch 45/100
35/35 [==============================] - 0s 702us/step - loss: 1.6127 - accuracy: 0.7849
Epoch 46/100
35/35 [==============================] - 0s 721us/step - loss: 2.9546 - accuracy: 0.7505
Epoch 47/100
35/35 [==============================] - 0s 718us/step - loss: 1.9538 - accuracy: 0.7387
Epoch 48/100
35/35 [==============================] - 0s 678us/step - loss: 1.1175 - accuracy: 0.7595
Epoch 49/100
35/35 [==============================] - 0s 721us/step - loss: 1.5095 - accuracy: 0.7423
Epoch 50/100
35/35 [==============================] - 0s 721us/step - loss: 2.3259 - accuracy: 0.7269
Epoch 51/100
35/35 [==============================] - 0s 709us/step - loss: 1.1819 - accuracy: 0.7477
Epoch 52/100
35/35 [==============================] - 0s 750us/step - loss: 1.2848 - accuracy: 0.7359
Epoch 53/100
35/35 [==============================] - 0s 735us/step - loss: 1.0187 - accuracy: 0.7495
Epoch 54/100
35/35 [==============================] - 0s 686us/step - loss: 1.3079 - accuracy: 0.7604
Epoch 55/100
35/35 [==============================] - 0s 712us/step - loss: 2.3703 - accuracy: 0.7296
Epoch 56/100
35/35 [==============================] - 0s 720us/step - loss: 2.6319 - accuracy: 0.7223
Epoch 57/100
35/35 [==============================] - 0s 721us/step - loss: 2.4734 - accuracy: 0.7187
Epoch 58/100
35/35 [==============================] - 0s 692us/step - loss: 1.3120 - accuracy: 0.7668
Epoch 59/100
35/35 [==============================] - 0s 736us/step - loss: 1.3796 - accuracy: 0.7287
Epoch 60/100
35/35 [==============================] - 0s 735us/step - loss: 1.4884 - accuracy: 0.7387
Epoch 61/100
35/35 [==============================] - 0s 721us/step - loss: 1.1142 - accuracy: 0.7586
Epoch 62/100
35/35 [==============================] - 0s 721us/step - loss: 1.2777 - accuracy: 0.7396
Epoch 63/100
35/35 [==============================] - 0s 678us/step - loss: 1.8927 - accuracy: 0.7505
Epoch 64/100
35/35 [==============================] - 0s 721us/step - loss: 1.2669 - accuracy: 0.7740
Epoch 65/100
35/35 [==============================] - 0s 721us/step - loss: 2.1518 - accuracy: 0.7232
Epoch 66/100
35/35 [==============================] - 0s 692us/step - loss: 1.0626 - accuracy: 0.7650
Epoch 67/100
35/35 [==============================] - 0s 707us/step - loss: 1.5640 - accuracy: 0.7713
Epoch 68/100
35/35 [==============================] - 0s 663us/step - loss: 1.4494 - accuracy: 0.7632
Epoch 69/100
35/35 [==============================] - 0s 707us/step - loss: 1.3005 - accuracy: 0.7586
Epoch 70/100
35/35 [==============================] - 0s 707us/step - loss: 1.0583 - accuracy: 0.7468
Epoch 71/100
35/35 [==============================] - 0s 692us/step - loss: 1.9220 - accuracy: 0.7368
Epoch 72/100
35/35 [==============================] - 0s 721us/step - loss: 2.1909 - accuracy: 0.7287
Epoch 73/100
35/35 [==============================] - 0s 693us/step - loss: 2.2556 - accuracy: 0.7659
Epoch 74/100
35/35 [==============================] - 0s 707us/step - loss: 1.4599 - accuracy: 0.7468
Epoch 75/100
35/35 [==============================] - 0s 706us/step - loss: 1.1778 - accuracy: 0.7387
Epoch 76/100
35/35 [==============================] - 0s 715us/step - loss: 1.0635 - accuracy: 0.7341
Epoch 77/100
35/35 [==============================] - 0s 721us/step - loss: 1.6573 - accuracy: 0.7495
Epoch 78/100
35/35 [==============================] - 0s 722us/step - loss: 1.7121 - accuracy: 0.7477
Epoch 79/100
35/35 [==============================] - 0s 765us/step - loss: 1.9005 - accuracy: 0.7450
Epoch 80/100
35/35 [==============================] - 0s 706us/step - loss: 1.8768 - accuracy: 0.7359
Epoch 81/100
35/35 [==============================] - 0s 692us/step - loss: 1.3129 - accuracy: 0.7468
Epoch 82/100
35/35 [==============================] - 0s 703us/step - loss: 3.4233 - accuracy: 0.7477
Epoch 83/100
35/35 [==============================] - 0s 721us/step - loss: 1.1533 - accuracy: 0.7477
Epoch 84/100
35/35 [==============================] - 0s 750us/step - loss: 1.1083 - accuracy: 0.7377
Epoch 85/100
35/35 [==============================] - 0s 693us/step - loss: 0.8883 - accuracy: 0.7495
Epoch 86/100
35/35 [==============================] - 0s 735us/step - loss: 0.9498 - accuracy: 0.7759
Epoch 87/100
35/35 [==============================] - 0s 721us/step - loss: 2.1869 - accuracy: 0.7232
Epoch 88/100
35/35 [==============================] - 0s 721us/step - loss: 1.0602 - accuracy: 0.7786
Epoch 89/100
35/35 [==============================] - 0s 677us/step - loss: 1.0324 - accuracy: 0.7332
Epoch 90/100
35/35 [==============================] - 0s 692us/step - loss: 0.7070 - accuracy: 0.7659
Epoch 91/100
35/35 [==============================] - 0s 721us/step - loss: 0.7761 - accuracy: 0.7886
Epoch 92/100
35/35 [==============================] - 0s 706us/step - loss: 0.8364 - accuracy: 0.7668
Epoch 93/100
35/35 [==============================] - 0s 722us/step - loss: 1.1085 - accuracy: 0.7505
Epoch 94/100
35/35 [==============================] - 0s 693us/step - loss: 1.1136 - accuracy: 0.7677
Epoch 95/100
35/35 [==============================] - 0s 692us/step - loss: 1.1943 - accuracy: 0.7232
Epoch 96/100
35/35 [==============================] - 0s 735us/step - loss: 1.1089 - accuracy: 0.7559
Epoch 97/100
35/35 [==============================] - 0s 736us/step - loss: 1.8851 - accuracy: 0.7559
Epoch 98/100
35/35 [==============================] - 0s 721us/step - loss: 1.6738 - accuracy: 0.7414
Epoch 99/100
35/35 [==============================] - 0s 691us/step - loss: 1.0614 - accuracy: 0.7477
Epoch 100/100
35/35 [==============================] - 0s 721us/step - loss: 1.0712 - accuracy: 0.7577

In [11]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

12/12 - 0s - loss: 3.8352 - accuracy: 0.8668 - 103ms/epoch - 9ms/step
Loss: 3.835178852081299, Accuracy: 0.866847813129425